[greeter]
background = /usr/share/backgrounds/black-god/blackgod-wallpaper.jpg
theme-name = Kali-Dark
icon-theme-name = Flat-Remix-Blue-Dark
font-name = Cantarell 11
xft-antialias = true
xft-dpi = 96
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %H:%M
default-user-image = #security-high
screensaver-timeout = 60
